ALTER TABLE RELIEFD RENAME COLUMN REPAIRCOMPANY  TO REPAIRCOMPANYTMP;
ALTER TABLE RELIEFD ADD (REPAIRCOMPANY NVARCHAR2(100));
UPDATE RELIEFD SET REPAIRCOMPANY = REPAIRCOMPANYTMP ;
ALTER TABLE RELIEFD DROP COLUMN REPAIRCOMPANYTMP ;

ALTER TABLE RELIEFD RENAME COLUMN CUSTOMERPO TO CUSTOMERPOTMP;
ALTER TABLE RELIEFD ADD (CUSTOMERPO NVARCHAR2(100));
UPDATE RELIEFD SET CUSTOMERPO = CUSTOMERPOTMP;
ALTER TABLE RELIEFD DROP COLUMN CUSTOMERPOTMP;

ALTER TABLE CV RENAME COLUMN REPAIRCOMPANY  TO REPAIRCOMPANYTMP;
ALTER TABLE CV ADD (REPAIRCOMPANY NVARCHAR2(100));
UPDATE CV SET REPAIRCOMPANY = REPAIRCOMPANYTMP ;
ALTER TABLE CV DROP COLUMN REPAIRCOMPANYTMP ;

ALTER TABLE CV RENAME COLUMN CUSTOMERPO TO CUSTOMERPOTMP;
ALTER TABLE CV ADD (CUSTOMERPO NVARCHAR2(100));
UPDATE CV SET CUSTOMERPO = CUSTOMERPOTMP;
ALTER TABLE CV DROP COLUMN CUSTOMERPOTMP;



select  R.REPAIRCOMPANY,R.CUSTOMERPO/*,R.REPAIRCOMPANYTMP,R.CUSTOMERPOTMP*/ from CV r  
where R.CUSTOMERPO is not null  


软件开发等全生命周期软件开发等全生命周期软件开发等

软件开发等 全生命周期 软件开发等 全生命周期 软件开发等


软件开发等全生命周期软件开发等全生命周期软件开发等软件开发等全生命周期软件开发等全生命周期软件开发等
软件开发等全生命周期软件开发等全生命周期软件开发等软件开发等全生命周期软件开发等全生命周期软件开发等
USPUPDATECVDETAIL

软件开发等全生命周期软件开发等全生命周期软件开发等软件开


Data Source=alpdmnq01-scan.tsg.ge.com:1521/onndwq01;Persist Security Info=no;User ID=DDSAFM;Password=dda12pwd;