REM INSERTING into EXPORT_TABLE
SET DEFINE OFF;
Insert into EXPORT_TABLE (SQL_ID,CHILD_NUMBER,SQL_TEXT,SQL_FULLTEXT,ELAPSED_TIME,CPU_TIME,DISK_READS,ELAPSED_RANK) values 
('1hgk1u0ynpjga',0,
' SELECT *  FROM (SELECT  a.UNIQUEKEY, a.MODELNUMBER,a.MOSTRECENT,a.TOTALCOST,a.LOOPNUMBER,''RV'' AS EQUIPTYPE,        
TAGNUMBER,SERIAL,DATETESTED,NEXTMAINDATE,NEXTTESTDATE,NEXTINSPDATE,        DECODE(ISDATE(DATETESTED),0,NULL,DATEDIFF(''DAY'',TO_DATE(DATETESTED,''yyyy/mm/dd''),CURRENT_DATE)) REPAIRDAYDUE,NEXTINSPDATE as DATEDUE,        DATEDIFF(''DAY'',CURRENT_DATE,TO_DATE(NEXTMAINDATE,''yyyy/mm/dd'')) DAYDUE,        FLOOR((DATEDIFF(''DAY'',CURRENT_DATE,TO_DATE(NEXTMAINDATE,''yyyy/mm/dd''))+TO_NUMBER(TO_CHAR(CURRENT_DATE,''D''))-1)/7) WEEKDUE,        DATEDIFF(''MONTH'',CURRENT_DATE,TO_DATE(NEXTMAINDATE,''yyyy/mm/dd'')) MONTHDUE,        DATEDIFF(''YEAR'',CURRENT_DATE,TO_DATE(NEXTMAINDATE,''yyyy/mm/dd'')) YEARDUE        FROM ReliefD a        JOIN TEMPKEYLIST b ON (b.UNIQUEKEY = a.UNIQUEKEY AND CREATEDATE = ''2018/09/27 09:42:34.038000000'')                 WHERE MOSTRECENT = ''T'' AND a.TENANTKEY= ''2892953897293E3DE0530100007FB676''  AND ISDATE(NEXTMAINDATE) = 1 AND NEXTMAINDATE BETWEEN ''1900/01/01'' AND ''9999/01/01''','	SELECT *  FROM (SELECT  a.UNIQUEKEY, a.MODELNUMBER,a.MOSTRECENT,a.TOTALCOST,a.LOOPNUMBER,'RV' AS EQUIPTYPE,
        TAGNUMBER,SERIAL,DATETESTED,NEXTMAINDATE,NEXTTESTDATE,NEXTINSPDATE,
        DECODE(ISDATE(DATETESTED),0,NULL,DATEDIFF('DAY',TO_DATE(DATETESTED,'yyyy/mm/dd'),CURRENT_DATE)) REPAIRDAYDUE,NEXTINSPDATE as DATEDUE,
        DATEDIFF('DAY',CURRENT_DATE,TO_DATE(NEXTMAINDATE,'yyyy/mm/dd')) DAYDUE,
        FLOOR((DATEDIFF('DAY',CURRENT_DATE,TO_DATE(NEXTMAINDATE,'yyyy/mm/dd'))+TO_NUMBER(TO_CHAR(CURRENT_DATE,'D'))-1)/7) WEEKDUE,
        DATEDIFF('MONTH',CURRENT_DATE,TO_DATE(NEXTMAINDATE,'yyyy/mm/dd')) MONTHDUE,
        DATEDIFF('YEAR',CURRENT_DATE,TO_DATE(NEXTMAINDATE,'yyyy/mm/dd')) YEARDUE
        FROM ReliefD a
        JOIN TEMPKEYLIST b ON (b.UNIQUEKEY = a.UNIQUEKEY AND CREATEDATE = '2018/09/27 09:42:34.038000000')
            
        WHERE MOSTRECENT = 'T' AND a.TENANTKEY= '2892953897293E3DE0530100007FB676'  AND ISDATE(NEXTMAINDATE) = 1 AND NEXTMAINDATE BETWEEN '1900/01/01' AND '9999/01/01') result',339052521,3859375,105946,1);
Insert into EXPORT_TABLE (SQL_ID,CHILD_NUMBER,SQL_TEXT,SQL_FULLTEXT,ELAPSED_TIME,CPU_TIME,DISK_READS,ELAPSED_RANK) values ('8yajg9qwsfqbw',0,' SELECT *  FROM (SELECT  a.UNIQUEKEY, a.MODELNUMBER,a.MOSTRECENT,a.TOTALCOST,a.LOOPNUMBER,''RV'' AS EQUIPTYPE,        TAGNUMBER,SERIAL,DATETESTED,NEXTMAINDATE,NEXTTESTDATE,NEXTINSPDATE,        DECODE(ISDATE(DATETESTED),0,NULL,DATEDIFF(''DAY'',TO_DATE(DATETESTED,''yyyy/mm/dd''),CURRENT_DATE)) REPAIRDAYDUE,NEXTINSPDATE as DATEDUE,        DATEDIFF(''DAY'',CURRENT_DATE,TO_DATE(NEXTMAINDATE,''yyyy/mm/dd'')) DAYDUE,        FLOOR((DATEDIFF(''DAY'',CURRENT_DATE,TO_DATE(NEXTMAINDATE,''yyyy/mm/dd''))+TO_NUMBER(TO_CHAR(CURRENT_DATE,''D''))-1)/7) WEEKDUE,        DATEDIFF(''MONTH'',CURRENT_DATE,TO_DATE(NEXTMAINDATE,''yyyy/mm/dd'')) MONTHDUE,        DATEDIFF(''YEAR'',CURRENT_DATE,TO_DATE(NEXTMAINDATE,''yyyy/mm/dd'')) YEARDUE        FROM ReliefD a        JOIN TEMPKEYLIST b ON (b.UNIQUEKEY = a.UNIQUEKEY AND CREATEDATE = ''2018/09/27 09:44:41.433000000'')                 WHERE MOSTRECENT = ''T'' AND a.TENANTKEY= ''2892953897293E3DE0530100007FB676''  AND ISDATE(NEXTMAINDATE) = 1 AND NEXTMAINDATE BETWEEN ''1900/01/01'' AND ''9999/01/01''','	SELECT *  FROM (SELECT  a.UNIQUEKEY, a.MODELNUMBER,a.MOSTRECENT,a.TOTALCOST,a.LOOPNUMBER,'RV' AS EQUIPTYPE,
        TAGNUMBER,SERIAL,DATETESTED,NEXTMAINDATE,NEXTTESTDATE,NEXTINSPDATE,
        DECODE(ISDATE(DATETESTED),0,NULL,DATEDIFF('DAY',TO_DATE(DATETESTED,'yyyy/mm/dd'),CURRENT_DATE)) REPAIRDAYDUE,NEXTINSPDATE as DATEDUE,
        DATEDIFF('DAY',CURRENT_DATE,TO_DATE(NEXTMAINDATE,'yyyy/mm/dd')) DAYDUE,
        FLOOR((DATEDIFF('DAY',CURRENT_DATE,TO_DATE(NEXTMAINDATE,'yyyy/mm/dd'))+TO_NUMBER(TO_CHAR(CURRENT_DATE,'D'))-1)/7) WEEKDUE,
        DATEDIFF('MONTH',CURRENT_DATE,TO_DATE(NEXTMAINDATE,'yyyy/mm/dd')) MONTHDUE,
        DATEDIFF('YEAR',CURRENT_DATE,TO_DATE(NEXTMAINDATE,'yyyy/mm/dd')) YEARDUE
        FROM ReliefD a
        JOIN TEMPKEYLIST b ON (b.UNIQUEKEY = a.UNIQUEKEY AND CREATEDATE = '2018/09/27 09:44:41.433000000')
            
        WHERE MOSTRECENT = 'T' AND a.TENANTKEY= '2892953897293E3DE0530100007FB676'  AND ISDATE(NEXTMAINDATE) = 1 AND NEXTMAINDATE BETWEEN '1900/01/01' AND '9999/01/01') result',317129939,3468750,79455,2);
Insert into EXPORT_TABLE (SQL_ID,CHILD_NUMBER,SQL_TEXT,SQL_FULLTEXT,ELAPSED_TIME,CPU_TIME,DISK_READS,ELAPSED_RANK) values ('9pcjm0cgav5fs',0,' BEGIN    SYS.KUPW$WORKER.MAIN(''SYS_IMPORT_TABLE_01'', ''VKC2'', 0);  END; ',' BEGIN
SYS.KUPW$WORKER.MAIN('SYS_IMPORT_TABLE_01', 'VKC2', 0);
END;
',215361843,50031250,41530,3);
Insert into EXPORT_TABLE (SQL_ID,CHILD_NUMBER,SQL_TEXT,SQL_FULLTEXT,ELAPSED_TIME,CPU_TIME,DISK_READS,ELAPSED_RANK) values 
('dxbyms83m0w4g',0,' SELECT *  FROM (SELECT  a.UNIQUEKEY, a.MODELNUMBER,a.MOSTRECENT,a.LOOPNUMBER,''RV'' AS EQUIPTYPE,        TAGNUMBER,SERIAL,DATETESTED,NEXTMAINDATE,NEXTTESTDATE,NEXTINSPDATE,        DECODE(ISDATE(DATETESTED),0,NULL,DATEDIFF(''DAY'',TO_DATE(DATETESTED,''yyyy/mm/dd''),CURRENT_DATE)) REPAIRDAYDUE,NEXTINSPDATE as DATEDUE,        DATEDIFF(''DAY'',CURRENT_DATE,TO_DATE(NEXTMAINDATE,''yyyy/mm/dd'')) DAYDUE,        FLOOR((DATEDIFF(''DAY'',CURRENT_DATE,TO_DATE(NEXTMAINDATE,''yyyy/mm/dd''))+TO_NUMBER(TO_CHAR(CURRENT_DATE,''D''))-1)/7) WEEKDUE,        DATEDIFF(''MONTH'',CURRENT_DATE,TO_DATE(NEXTMAINDATE,''yyyy/mm/dd'')) MONTHDUE,        DATEDIFF(''YEAR'',CURRENT_DATE,TO_DATE(NEXTMAINDATE,''yyyy/mm/dd'')) YEARDUE        FROM ReliefD a        JOIN TEMPKEYLIST b ON (b.UNIQUEKEY = a.UNIQUEKEY AND CREATEDATE = ''2018/09/27 11:41:52.668000000'')                 WHERE MOSTRECENT = ''T'' AND a.TENANTKEY= ''2892953897293E3DE0530100007FB676''  AND ISDATE(NEXTMAINDATE) = 1 AND NEXTMAINDATE BETWEEN ''1900/01/01'' AND ''9999/01/01'') result','	SELECT *  FROM (SELECT  a.UNIQUEKEY, a.MODELNUMBER,a.MOSTRECENT,a.LOOPNUMBER,'RV' AS EQUIPTYPE,
        TAGNUMBER,SERIAL,DATETESTED,NEXTMAINDATE,NEXTTESTDATE,NEXTINSPDATE,
        DECODE(ISDATE(DATETESTED),0,NULL,DATEDIFF('DAY',TO_DATE(DATETESTED,'yyyy/mm/dd'),CURRENT_DATE)) REPAIRDAYDUE,NEXTINSPDATE as DATEDUE,
        DATEDIFF('DAY',CURRENT_DATE,TO_DATE(NEXTMAINDATE,'yyyy/mm/dd')) DAYDUE,
        FLOOR((DATEDIFF('DAY',CURRENT_DATE,TO_DATE(NEXTMAINDATE,'yyyy/mm/dd'))+TO_NUMBER(TO_CHAR(CURRENT_DATE,'D'))-1)/7) WEEKDUE,
        DATEDIFF('MONTH',CURRENT_DATE,TO_DATE(NEXTMAINDATE,'yyyy/mm/dd')) MONTHDUE,
        DATEDIFF('YEAR',CURRENT_DATE,TO_DATE(NEXTMAINDATE,'yyyy/mm/dd')) YEARDUE
        FROM ReliefD a
        JOIN TEMPKEYLIST b ON (b.UNIQUEKEY = a.UNIQUEKEY AND CREATEDATE = '2018/09/27 11:41:52.668000000')
            
        WHERE MOSTRECENT = 'T' AND a.TENANTKEY= '2892953897293E3DE0530100007FB676'  AND ISDATE(NEXTMAINDATE) = 1 AND
         NEXTMAINDATE BETWEEN '1900/01/01' AND '9999/01/01') result',
        
        187313003,3437500,76041,4);
Insert into EXPORT_TABLE (SQL_ID,CHILD_NUMBER,SQL_TEXT,SQL_FULLTEXT,ELAPSED_TIME,CPU_TIME,DISK_READS,ELAPSED_RANK) values ('6mjsx3z4t4rzc',0,' SELECT *  FROM (SELECT  a.UNIQUEKEY, a.MODELNUMBER,a.MOSTRECENT,a.UNIQUEKEY UKEY,a.LOOPNUMBER,''RV'' AS EQUIPTYPE,        TAGNUMBER,SERIAL,DATETESTED,NEXTMAINDATE,NEXTTESTDATE,NEXTINSPDATE,        DECODE(ISDATE(DATETESTED),0,NULL,DATEDIFF(''DAY'',TO_DATE(DATETESTED,''yyyy/mm/dd''),CURRENT_DATE)) REPAIRDAYDUE,NEXTINSPDATE as DATEDUE,        DATEDIFF(''DAY'',CURRENT_DATE,TO_DATE(NEXTMAINDATE,''yyyy/mm/dd'')) DAYDUE,        FLOOR((DATEDIFF(''DAY'',CURRENT_DATE,TO_DATE(NEXTMAINDATE,''yyyy/mm/dd''))+TO_NUMBER(TO_CHAR(CURRENT_DATE,''D''))-1)/7) WEEKDUE,        DATEDIFF(''MONTH'',CURRENT_DATE,TO_DATE(NEXTMAINDATE,''yyyy/mm/dd'')) MONTHDUE,        DATEDIFF(''YEAR'',CURRENT_DATE,TO_DATE(NEXTMAINDATE,''yyyy/mm/dd'')) YEARDUE        FROM ReliefD a        JOIN TEMPKEYLIST b ON (b.UNIQUEKEY = a.UNIQUEKEY AND CREATEDATE = ''2018/09/27 11:38:38.753000000'')                 WHERE MOSTRECENT = ''T'' AND a.TENANTKEY= ''2892953897293E3DE0530100007FB676''  AND ISDATE(NEXTMAINDATE) = 1 AND NEXTMAINDATE BETWEEN ''1900/01/01'' AND ''9999/0','	SELECT *  FROM (SELECT  a.UNIQUEKEY, a.MODELNUMBER,a.MOSTRECENT,a.UNIQUEKEY UKEY,a.LOOPNUMBER,'RV' AS EQUIPTYPE,
        TAGNUMBER,SERIAL,DATETESTED,NEXTMAINDATE,NEXTTESTDATE,NEXTINSPDATE,
        DECODE(ISDATE(DATETESTED),0,NULL,DATEDIFF('DAY',TO_DATE(DATETESTED,'yyyy/mm/dd'),CURRENT_DATE)) REPAIRDAYDUE,NEXTINSPDATE as DATEDUE,
        DATEDIFF('DAY',CURRENT_DATE,TO_DATE(NEXTMAINDATE,'yyyy/mm/dd')) DAYDUE,
        FLOOR((DATEDIFF('DAY',CURRENT_DATE,TO_DATE(NEXTMAINDATE,'yyyy/mm/dd'))+TO_NUMBER(TO_CHAR(CURRENT_DATE,'D'))-1)/7) WEEKDUE,
        DATEDIFF('MONTH',CURRENT_DATE,TO_DATE(NEXTMAINDATE,'yyyy/mm/dd')) MONTHDUE,
        DATEDIFF('YEAR',CURRENT_DATE,TO_DATE(NEXTMAINDATE,'yyyy/mm/dd')) YEARDUE
        FROM ReliefD a
        JOIN TEMPKEYLIST b ON (b.UNIQUEKEY = a.UNIQUEKEY AND CREATEDATE = '2018/09/27 11:38:38.753000000')
            
        WHERE MOSTRECENT = 'T' AND a.TENANTKEY= '2892953897293E3DE0530100007FB676'  AND ISDATE(NEXTMAINDATE) = 1 AND NEXTMAINDATE BETWEEN '1900/01/01' AND '9999/01/01') result',184200060,3062500,76112,5);
Insert into EXPORT_TABLE (SQL_ID,CHILD_NUMBER,SQL_TEXT,SQL_FULLTEXT,ELAPSED_TIME,CPU_TIME,DISK_READS,ELAPSED_RANK) values ('cc5sw31cx9h8t',0,' SELECT *  FROM (SELECT  a.UNIQUEKEY, a.MODELNUMBER,a.MOSTRECENT,a.TOTALCOST,a.LOOPNUMBER,''RV'' AS EQUIPTYPE,        TAGNUMBER,SERIAL,DATETESTED,NEXTMAINDATE,NEXTTESTDATE,NEXTINSPDATE,        DECODE(ISDATE(DATETESTED),0,NULL,DATEDIFF(''DAY'',TO_DATE(DATETESTED,''yyyy/mm/dd''),CURRENT_DATE)) REPAIRDAYDUE,NEXTINSPDATE as DATEDUE,        DATEDIFF(''DAY'',CURRENT_DATE,TO_DATE(NEXTMAINDATE,''yyyy/mm/dd'')) DAYDUE,        FLOOR((DATEDIFF(''DAY'',CURRENT_DATE,TO_DATE(NEXTMAINDATE,''yyyy/mm/dd''))+TO_NUMBER(TO_CHAR(CURRENT_DATE,''D''))-1)/7) WEEKDUE,        DATEDIFF(''MONTH'',CURRENT_DATE,TO_DATE(NEXTMAINDATE,''yyyy/mm/dd'')) MONTHDUE,        DATEDIFF(''YEAR'',CURRENT_DATE,TO_DATE(NEXTMAINDATE,''yyyy/mm/dd'')) YEARDUE        FROM ReliefD a        JOIN TEMPKEYLIST b ON (b.UNIQUEKEY = a.UNIQUEKEY AND CREATEDATE = ''2018/09/27 11:27:20.508000000'')                 WHERE MOSTRECENT = ''T'' AND a.TENANTKEY= ''2892953897293E3DE0530100007FB676''  AND ISDATE(NEXTMAINDATE) = 1 AND NEXTMAINDATE BETWEEN ''1900/01/01'' AND ''9999/01/01''','	SELECT *  FROM (SELECT  a.UNIQUEKEY, a.MODELNUMBER,a.MOSTRECENT,a.TOTALCOST,a.LOOPNUMBER,'RV' AS EQUIPTYPE,
        TAGNUMBER,SERIAL,DATETESTED,NEXTMAINDATE,NEXTTESTDATE,NEXTINSPDATE,
        DECODE(ISDATE(DATETESTED),0,NULL,DATEDIFF('DAY',TO_DATE(DATETESTED,'yyyy/mm/dd'),CURRENT_DATE)) REPAIRDAYDUE,NEXTINSPDATE as DATEDUE,
        DATEDIFF('DAY',CURRENT_DATE,TO_DATE(NEXTMAINDATE,'yyyy/mm/dd')) DAYDUE,
        FLOOR((DATEDIFF('DAY',CURRENT_DATE,TO_DATE(NEXTMAINDATE,'yyyy/mm/dd'))+TO_NUMBER(TO_CHAR(CURRENT_DATE,'D'))-1)/7) WEEKDUE,
        DATEDIFF('MONTH',CURRENT_DATE,TO_DATE(NEXTMAINDATE,'yyyy/mm/dd')) MONTHDUE,
        DATEDIFF('YEAR',CURRENT_DATE,TO_DATE(NEXTMAINDATE,'yyyy/mm/dd')) YEARDUE
        FROM ReliefD a
        JOIN TEMPKEYLIST b ON (b.UNIQUEKEY = a.UNIQUEKEY AND CREATEDATE = '2018/09/27 11:27:20.508000000')
            
        WHERE MOSTRECENT = 'T' AND a.TENANTKEY= '2892953897293E3DE0530100007FB676'  AND ISDATE(NEXTMAINDATE) = 1 AND NEXTMAINDATE BETWEEN '1900/01/01' AND '9999/01/01') result',183926220,3562500,77826,6);
Insert into EXPORT_TABLE (SQL_ID,CHILD_NUMBER,SQL_TEXT,SQL_FULLTEXT,ELAPSED_TIME,CPU_TIME,DISK_READS,ELAPSED_RANK) values ('47r1y8yn34jmj',0,'select default$ from col$ where rowid=:1','select default$ from col$ where rowid=:1',179412585,175531250,20,7);
Insert into EXPORT_TABLE (SQL_ID,CHILD_NUMBER,SQL_TEXT,SQL_FULLTEXT,ELAPSED_TIME,CPU_TIME,DISK_READS,ELAPSED_RANK) values ('cj0a08684mchz',0,' SELECT *  FROM (SELECT  a.UNIQUEKEY, a.MODELNUMBER,a.MOSTRECENT,a.TOTALCOST,a.LOOPNUMBER,''RV'' AS EQUIPTYPE,        TAGNUMBER,SERIAL,DATETESTED,NEXTMAINDATE,NEXTTESTDATE,NEXTINSPDATE,        DECODE(ISDATE(DATETESTED),0,NULL,DATEDIFF(''DAY'',TO_DATE(DATETESTED,''yyyy/mm/dd''),CURRENT_DATE)) REPAIRDAYDUE,NEXTINSPDATE as DATEDUE,        DATEDIFF(''DAY'',CURRENT_DATE,TO_DATE(NEXTMAINDATE,''yyyy/mm/dd'')) DAYDUE,        FLOOR((DATEDIFF(''DAY'',CURRENT_DATE,TO_DATE(NEXTMAINDATE,''yyyy/mm/dd''))+TO_NUMBER(TO_CHAR(CURRENT_DATE,''D''))-1)/7) WEEKDUE,        DATEDIFF(''MONTH'',CURRENT_DATE,TO_DATE(NEXTMAINDATE,''yyyy/mm/dd'')) MONTHDUE,        DATEDIFF(''YEAR'',CURRENT_DATE,TO_DATE(NEXTMAINDATE,''yyyy/mm/dd'')) YEARDUE        FROM ReliefD a        JOIN TEMPKEYLIST b ON (b.UNIQUEKEY = a.UNIQUEKEY AND CREATEDATE = ''2018/09/27 11:33:58.749000000'')                 WHERE MOSTRECENT = ''T'' AND a.TENANTKEY= ''2892953897293E3DE0530100007FB676''  AND ISDATE(NEXTMAINDATE) = 1 AND NEXTMAINDATE BETWEEN ''1900/01/01'' AND ''9999/01/01''','	SELECT *  FROM (SELECT  a.UNIQUEKEY, a.MODELNUMBER,a.MOSTRECENT,a.TOTALCOST,a.LOOPNUMBER,'RV' AS EQUIPTYPE,
        TAGNUMBER,SERIAL,DATETESTED,NEXTMAINDATE,NEXTTESTDATE,NEXTINSPDATE,
        DECODE(ISDATE(DATETESTED),0,NULL,DATEDIFF('DAY',TO_DATE(DATETESTED,'yyyy/mm/dd'),CURRENT_DATE)) REPAIRDAYDUE,NEXTINSPDATE as DATEDUE,
        DATEDIFF('DAY',CURRENT_DATE,TO_DATE(NEXTMAINDATE,'yyyy/mm/dd')) DAYDUE,
        FLOOR((DATEDIFF('DAY',CURRENT_DATE,TO_DATE(NEXTMAINDATE,'yyyy/mm/dd'))+TO_NUMBER(TO_CHAR(CURRENT_DATE,'D'))-1)/7) WEEKDUE,
        DATEDIFF('MONTH',CURRENT_DATE,TO_DATE(NEXTMAINDATE,'yyyy/mm/dd')) MONTHDUE,
        DATEDIFF('YEAR',CURRENT_DATE,TO_DATE(NEXTMAINDATE,'yyyy/mm/dd')) YEARDUE
        FROM ReliefD a
        JOIN TEMPKEYLIST b ON (b.UNIQUEKEY = a.UNIQUEKEY AND CREATEDATE = '2018/09/27 11:33:58.749000000')
            
        WHERE MOSTRECENT = 'T' AND a.TENANTKEY= '2892953897293E3DE0530100007FB676'  AND ISDATE(NEXTMAINDATE) = 1 AND NEXTMAINDATE BETWEEN '1900/01/01' AND '9999/01/01') result',173267229,3312500,76147,8);
Insert into EXPORT_TABLE (SQL_ID,CHILD_NUMBER,SQL_TEXT,SQL_FULLTEXT,ELAPSED_TIME,CPU_TIME,DISK_READS,ELAPSED_RANK) values ('dkw1wnqk5yy53',0,'Begin uspGetGridField(:v0, :v1, :v2, :v3, :v4, :v5, :v6, :v7, :v8); End;','Begin uspGetGridField(:v0, :v1, :v2, :v3, :v4, :v5, :v6, :v7, :v8); End;',161013836,63625000,17234,9);
Insert into EXPORT_TABLE (SQL_ID,CHILD_NUMBER,SQL_TEXT,SQL_FULLTEXT,ELAPSED_TIME,CPU_TIME,DISK_READS,ELAPSED_RANK) values ('g25sutzr7vgzh',0,' SELECT *  FROM (SELECT  a.UNIQUEKEY, a.MODELNUMBER,a.MOSTRECENT,a.UNIQUEKEY UKEY,a.LOOPNUMBER,''RV'' AS EQUIPTYPE,        TAGNUMBER,SERIAL,DATETESTED,NEXTMAINDATE,NEXTTESTDATE,NEXTINSPDATE,        DECODE(ISDATE(DATETESTED),0,NULL,DATEDIFF(''DAY'',TO_DATE(DATETESTED,''yyyy/mm/dd''),CURRENT_DATE)) REPAIRDAYDUE,NEXTINSPDATE as DATEDUE,        DATEDIFF(''DAY'',CURRENT_DATE,TO_DATE(NEXTMAINDATE,''yyyy/mm/dd'')) DAYDUE,        FLOOR((DATEDIFF(''DAY'',CURRENT_DATE,TO_DATE(NEXTMAINDATE,''yyyy/mm/dd''))+TO_NUMBER(TO_CHAR(CURRENT_DATE,''D''))-1)/7) WEEKDUE,        DATEDIFF(''MONTH'',CURRENT_DATE,TO_DATE(NEXTMAINDATE,''yyyy/mm/dd'')) MONTHDUE,        DATEDIFF(''YEAR'',CURRENT_DATE,TO_DATE(NEXTMAINDATE,''yyyy/mm/dd'')) YEARDUE        FROM ReliefD a        JOIN TEMPKEYLIST b ON (b.UNIQUEKEY = a.UNIQUEKEY AND CREATEDATE = ''2018/09/27 11:58:45.245000000'')                 WHERE MOSTRECENT = ''T'' AND a.TENANTKEY= ''2892953897293E3DE0530100007FB676''  AND ISDATE(NEXTMAINDATE) = 1 AND NEXTMAINDATE BETWEEN ''1900/01/01'' AND ''9999/0','	SELECT *  FROM (SELECT  a.UNIQUEKEY, a.MODELNUMBER,a.MOSTRECENT,a.UNIQUEKEY UKEY,a.LOOPNUMBER,'RV' AS EQUIPTYPE,
        TAGNUMBER,SERIAL,DATETESTED,NEXTMAINDATE,NEXTTESTDATE,NEXTINSPDATE,
        DECODE(ISDATE(DATETESTED),0,NULL,DATEDIFF('DAY',TO_DATE(DATETESTED,'yyyy/mm/dd'),CURRENT_DATE)) REPAIRDAYDUE,NEXTINSPDATE as DATEDUE,
        DATEDIFF('DAY',CURRENT_DATE,TO_DATE(NEXTMAINDATE,'yyyy/mm/dd')) DAYDUE,
        FLOOR((DATEDIFF('DAY',CURRENT_DATE,TO_DATE(NEXTMAINDATE,'yyyy/mm/dd'))+TO_NUMBER(TO_CHAR(CURRENT_DATE,'D'))-1)/7) WEEKDUE,
        DATEDIFF('MONTH',CURRENT_DATE,TO_DATE(NEXTMAINDATE,'yyyy/mm/dd')) MONTHDUE,
        DATEDIFF('YEAR',CURRENT_DATE,TO_DATE(NEXTMAINDATE,'yyyy/mm/dd')) YEARDUE
        FROM ReliefD a
        JOIN TEMPKEYLIST b ON (b.UNIQUEKEY = a.UNIQUEKEY AND CREATEDATE = '2018/09/27 11:58:45.245000000')
            
        WHERE MOSTRECENT = 'T' AND a.TENANTKEY= '2892953897293E3DE0530100007FB676'  AND ISDATE(NEXTMAINDATE) = 1 AND NEXTMAINDATE BETWEEN '1900/01/01' AND '9999/01/01') result',159650270,3171875,74568,10);
