SELECT * FROM (SELECT r.UNIQUEKEY,r.PLANTKEY,r.TAGNUMBER EQUIPMENTNAME,r.MOSTRECENT,r.DATETESTED,r.NEXTTESTDATE,r.NEXTMAINDATE,
r.EQUIPMENTKEY,r.TAGNUMBER,r.LOOPNUMBER,r.SERIAL,r.MANUFACTURER,r.MODELNUMBER,r.NEXTMAINFREQ,r.NEXTTESTFREQ,r.NEXTINSPFREQ,r.TRAVELLER,
IIF(ISDATE(DATETESTED)=1,DATETESTED,IIF(ISDATE(DATERECEIVED)=1,DATERECEIVED,substring(DATECREATE from 1 for 4)||'/'|| substring(DATECREATE from 5 for 2) 
||'/'|| substring(DATECREATE from 7 for 2))) DATETESTEDEFFECTIVE,
(SELECT COUNT(*) FROM PARTS PARTS WHERE PARTS.REPAIRENTRYKEY = r.UNIQUEKEY AND ( 1=1 ) )
 PARTFILTERCOUNT,(SELECT COUNT(*) FROM PARTS t WHERE t.REPAIRENTRYKEY = r.UNIQUEKEY AND WORKPERFORMED CONTAINING 'REPLACE') PARTREPLACEDCOUNT,
 (SELECT T.PARTTOPLACECOUNT FROM PREVREPAIRPARTTOPLACECOUNT T WHERE T.REPAIRENTRYKEY = R.UNIQUEKEY AND T.EQUIPTYPE=0 ) PARTTOREPLACECOUNT,(SELECT  
 VD.NEXTMAINDATE FROM USPGETPREVIOUSREPAIRENTRYKEY(R.UNIQUEKEY, 0) P LEFT JOIN RELIEFD VD ON VD.UNIQUEKEY = P.PREVIOUSREPAIRENTRYKEY) PRENEXTMAINDATE,
 (SELECT  VD.NEXTTESTDATE FROM USPGETPREVIOUSREPAIRENTRYKEY(R.UNIQUEKEY, 0) P LEFT JOIN RELIEFD VD ON VD.UNIQUEKEY = P.PREVIOUSREPAIRENTRYKEY) 
 PRENEXTTESTDATE FROM RELIEFD r  
WHERE  OWNERKEY = '20070927170902017037'  AND ( 1=1 )) 

WHERE PARTFILTERCOUNT > 0 