userkey 3406850899294951919 
test 615194523295858252

SELECT p.RETMULDATASETS, p.SQL
FROM uspGetNextMaintList('615194523295858252', null, null, null, null, 'T', 'T', null, 
null, null, 'uspGetCVList', 'DATETESTED', '1900/01/01', '9999/01/01', 'ALL', null, 
null, '1=1') p


select * from TEMPKEYLIST



DELETE FROM TEMPKEYLIST;
INSERT INTO TEMPKEYLIST
(
UNIQUEKEY,
CREATEDATE
)

SELECT	p.UNIQUEKEY ,CAST (CURRENT_TIMESTAMP AS VARCHAR(30))
FROM	USPGETKEYLISTBYFILTER('615194523295858252', null, null, null, null, 'T', 'T', null, 
null, null, 'uspGetCVList', 'DATETESTED', null,null, '1=1') p;


select * from TEMPKEYLIST

SELECT	UNIQUEKEY
FROM	USPGETKEYLISTBYFITLERCLAUSE('RELIEFD', '615194523295858252', null, null, 'UNIQUEKEY', 'F')			




SELECT	*
FROM	GRIDFILTER
WHERE	USERKEY = '615194523295858252'
--AND		GRIDDATASOURCE = 'uspGetCVList'
AND		MOSTRECENT = 'T'



--0326

http://localhost/VKV6/Repairs/Parts.aspx?showrv=True&showcv=False&showlv=False&showmov=False&showingrid=False&usingfield=NEXTINSPDATE&partsreplaced=True&partstobereplaced=False&partsonorder=False



SELECT p.RETMULDATASETS, p.SQL
FROM USPGETMTBF('615194523295858252', null, null, null, null, 
'T', 'T', 'F', 'F', 'F', 'uspGetCVList', 
'NEXTMAINDATE', '1=1', 'F', 'F') p

	DELETE FROM TEMPKEYLIST;
	
	INSERT INTO TEMPKEYLIST
	(
		UNIQUEKEY,
		CREATEDATE
	)
	SELECT	p.UNIQUEKEY ,CAST (CURRENT_TIMESTAMP AS VARCHAR(30))
	FROM	USPGETKEYLISTBYFILTER('615194523295858252', null, null, null, null, 
'T', 'T', 'F', 'F', 'F', 'uspGetCVList', 
'NEXTMAINDATE', NULL, NULL, null) p;


SELECT	UNIQUEKEY
FROM	USPGETKEYLISTBYFITLERCLAUSE('RELIEFD', 
:IN_USERKEY, :IN_FILTERCLAUSE, :IN_RVKeys, :IN_KEYNAME, :IN_ALLOWNERSPLANTS)			


	SELECT	FILTERSQLVALUE
	FROM	GRIDFILTER
	WHERE	USERKEY = '615194523295858252'
	AND		GRIDDATASOURCE = 'uspGetRVList'
	AND		MOSTRECENT = 'T'



SELECT p.*
FROM USPGETPARTSFORANALYSIS('3406850899294951919', '20061208100325022071', '20061208100325022071', '20061208100325022071', '20061208100325022071', 
'T', 'F', 'F', 'F', 
'F', null, 'NEXTINSPDATE', null, null, '1=1','T', 'F', 'F', 'F', 0,  'F', 'F') p





SELECT B.UNIQUEKEY,  
			CASE 
			WHEN D.DATEDUE IS NOT NULL THEN D.DATEDUE
			WHEN M.DATEDUE IS NOT NULL THEN M.DATEDUE
			WHEN R.NEXTINSPDATE IS NOT NULL THEN R.NEXTINSPDATE
			WHEN CV.NEXTINSPDATE IS NOT NULL THEN CV.NEXTINSPDATE
			END AS NEXTINSPDATE,
			
			B.OWNERKEY,B.PLANTKEY,B.EQUIPTRACKKEY,B.REPAIRENTRYKEY,
			B.EQUIPMENTTYPE,B.EQUIPNUM,B.TAGNUMBER,B.LOOPNUMBER,B.EXTRA,B.PARTDATE,
			B.PARTNUMBER,B.PARTNAME,B.CONDREC,B.CONDREC1,B.MATERIAL,B.SOURCE,B.PRICE,B.COST,B.WORKPERFORMED,B.RECOMMENDATION,B.UNIV1,B.UNIV2,
			B.DELIVERYDATE,B.PRICEUNIT,B.QUANTITY,B.EXTPRICE,B.EXTCOST,B.EI1,B.EI2,B.WORKPERFORMED1,B.NOTE1,B.E5,B.E6,B.E7,B.N1,B.N2,B.EI11,
			B.EI12,B.EXTRA100,B.EXTRA101,B.EXTRA102,B.EXTRA103,B.EXTRA104,B.N100,B.N101,B.RECPOSTEDBY,B.HYDROTESTSTAMP,B.RECCREATEDBY,B.AUNIV2,
			B.AUNIV3,B.AUNIV4,B.AUNIV5,B.COMMENTLOCAL,B.HEATNUMBER,B.CERTMATTSTRPT,B.CERTOFCONFORM,B.INVISIBLEINVKV,B.L11,B.L12,B.L13,B.L14,B.L15,
			B.PARTONORDER,B.RECSPARE,(SELECT t.PREVRECOMMENDATION FROM PARTPREVRECOMMENDATION t WHERE t.PARTUNIQUEKEY = B.UNIQUEKEY) PREVRECOMMENDATION,
			(SELECT t.PREVWORKPERFORMED FROM PARTPREVWORKPERFORMED t WHERE t.PARTUNIQUEKEY = B.UNIQUEKEY) PREVWORKPERFORMED FROM Parts B LEFT JOIN 
			LINEV D ON D.UNIQUEKEY = B.REPAIRENTRYKEY 
			LEFT JOIN MOV M ON M.UNIQUEKEY = B.REPAIRENTRYKEY 
			LEFT JOIN RELIEFD R ON R.UNIQUEKEY = B.REPAIRENTRYKEY 
			LEFT JOIN CV ON CV.UNIQUEKEY = B.REPAIRENTRYKEY WHERE B.UNIQUEKEY IN 
 (SELECT DISTINCT a.UNIQUEKEY FROM Parts a  WHERE 1=1  AND  1=1  and  (a.InvisibleInVKV = 'F' and a.InvisibleInVKV is not null)  
 AND (1<>1  OR a.WorkPerformed Containing 'replace'  ))



 USPGETPARTSFORANALYSIS


 CREATE INDEX IDX_UNIQUEKEY ON TEMPKEYLIST(UNIQUEKEY);


 0328
 PREVREPAIRPARTTOPLACECOUNT


 SELECT p.*
FROM USPGETRVLISTBYUSER('3406850899294951919', NULL, NULL, 'F', 'F', 'F', 'F', 1, 'T', NULL, NULL, NULL, 
' OR ', 'F', 'F', 'F','F', 'F', 'F', 'F', 'F', 'F', 'F') p
SELECT * FROM (SELECT r.UNIQUEKEY,r.PLANTKEY,r.TAGNUMBER EQUIPMENTNAME,r.MOSTRECENT,r.DATETESTED,r.NEXTTESTDATE,r.NEXTMAINDATE,
r.EQUIPMENTKEY,r.TAGNUMBER,r.LOOPNUMBER,r.SERIAL,r.MANUFACTURER,r.MODELNUMBER,r.NEXTMAINFREQ,r.NEXTTESTFREQ,r.NEXTINSPFREQ,r.TRAVELLER,r.LEAKEDATPRESS
,(SELECT T.PARTTOPLACECOUNT FROM PREVREPAIRPARTTOPLACECOUNT T WHERE T.REPAIRENTRYKEY = R.UNIQUEKEY AND T.EQUIPTYPE=0 ) PARTTOREPLACECOUNT,

( SELECT COUNT(T.REPAIRENTRYKEY) FROM PARTS T, USPGETPREVIOUSREPAIRENTRYKEY(R.UNIQUEKEY, 0) P WHERE T.REPAIRENTRYKEY = p.PREVIOUSREPAIRENTRYKEY  
AND ( T.RECOMMENDATION CONTAINING 'REPLACE' OR T.RECOMMENDATION CONTAINING 'NEXT' OR T.RECSPARE = 'T') )  testcol
FROM RELIEFD r  WHERE PLANTKEY = '20030319103909097704' 
 AND ((NEXTMAINDATE BETWEEN '1900/01/01' AND '2018/04/01' OR NEXTTESTDATE BETWEEN '1900/01/01' AND '2018/04/01')) AND ( 1=1  ))



PartToPlaceCountColumn = '(SELECT T.PARTTOPLACECOUNT FROM USPGETALLPREVRPRPARTTORPLCOUNT(0,R.EQUIPMENTKEY) T WHERE T.REPAIRENTRYKEY = R.UNIQUEKEY ) PARTTOREPLACECOUNT';

CommentPreviousEventCol = '(SELECT t.COMMENTPREVIOUSEVENT FROM USPGETALLPREVREPAIRCOMMENT(0,R.EQUIPMENTKEY) t WHERE t.REPAIRENTRYKEY = r.UNIQUEKEY) COMMENTPREVIOUSEVENT';	
PartCountPreviousEventCol = '(SELECT t.PARTCOUNTPREVEVENT FROM uspGetAllPrevRepairPartCount(0,R.EQUIPMENTKEY) t WHERE t.REPAIRENTRYKEY = r.UNIQUEKEY) PARTCOUNTPREVIOUSEVENT';



USPGETALLPREVRPRPARTTORPLCOUNT
USPGETALLPREVREPAIRCOMMENT
uspGetAllPrevRepairPartCount

ALTER TRIGGER PARTS_AFTER_CHANGE INACTIVE;
ALTER TRIGGER CV_AFTER_CHANGE INACTIVE;
ALTER TRIGGER LINEV_AFTER_CHANGE INACTIVE;
ALTER TRIGGER MOV_AFTER_CHANGE INACTIVE;
ALTER TRIGGER RELIEFD_AFTER_CHANGE INACTIVE;

1122.sql USPGETALLPREVREPAIRCOMMENT USPGETALLPREVREPAIRPARTCOUNT 
0130.sql uspGetAllPrevRprPartToRplCount
0206.sql USPGETPREVPARTSRECOMANDWORKP


PrevRecommendationCol = '(SELECT t.PREVRECOMMENDATION FROM USPGETPREVPARTSRECOMANDWORKP('|| IN_EQUIPTYPE ||',B.EQUIPTRACKKEY) t  WHERE t.PARTUNIQUEKEY = B.UNIQUEKEY) PREVRECOMMENDATION';
PrevWorkPerfCol = '(SELECT t.PREVWORKPERFORMED FROM USPGETPREVPARTSRECOMANDWORKP('|| IN_EQUIPTYPE ||',B.EQUIPTRACKKEY) t  WHERE t.PARTUNIQUEKEY = B.UNIQUEKEY) PREVWORKPERFORMED';

PrevRecommendationCol = '(SELECT t.PREVRECOMMENDATION FROM USPGETPREVPARTSRECOMAND('|| IN_EQUIPTYPE ||',B.EQUIPTRACKKEY) t  WHERE t.PARTUNIQUEKEY = B.UNIQUEKEY) PREVRECOMMENDATION';
PrevWorkPerfCol = '(SELECT t.PREVWORKPERFORMED FROM USPGETPREVPARTSWORKP('|| IN_EQUIPTYPE ||',B.EQUIPTRACKKEY) t  WHERE t.PARTUNIQUEKEY = B.UNIQUEKEY) PREVWORKPERFORMED';


uspGetAllPrevRepairComment












