

SELECT result.*,  
(TOTALMONTHS / ((CASE NUMOFEVENTS WHEN 1 THEN 2 ELSE NUMOFEVENTS END) - 1)) 
AS ACTFREQUENCY 

FROM 

(SELECT  a.UNIQUEKEY, a.EQUIPMENTKEY, a.TAGNUMBER,a.DATERECEIVED,
a.LOOPNUMBER,
 'RV' AS EQUIPTYPE,  		 
DATETESTED,    
NEXTMAINDATE,
NEXTTESTDATE, 
DATERECEIVED,
COALESCE((SELECT DATEDIFF(MONTH, CAST(MIN(DATETESTED) AS DATE),CAST(MAX(DATETESTED) AS DATE))  
FROM  ReliefD  WHERE equipmentkey = a.equipmentkey AND ISDATE(DATETESTED) = 1), 0) 
AS TOTALMONTHS,
(SELECT COUNT(1)  FROM ReliefD WHERE equipmentkey = a.equipmentkey) AS NUMOFEVENTS,
NEXTMAINFREQ,
NEXTTESTFREQ,
NEXTINSPFREQ,
(SELECT MAX(DATETESTED)  FROM   ReliefD  
WHERE equipmentkey = a.equipmentkey) AS MAXDATE ,  MOSTRECENT  
FROM    ReliefD a
JOIN	TEMPKEYLIST b ON (b.UNIQUEKEY = a.UNIQUEKEY AND CREATEDATE = '2018-03-22 15:21:11.5530')
) result WHERE ISDATE(MAXDATE)=1 